services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Undkonsorten\Easychat\:
    resource: '../Classes/*'


  Undkonsorten\Easychat\Command\DeleteSessionsCommand:
    tags:
      - name: 'console.command'
        command: 'easychat:delete-sessions'
        description: 'Deletes sessions older than given date interval.'
